/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./components/Bar.tsx')['default']
    CommonPop: typeof import('./components/CommonPop.vue')['default']
    copy: typeof import('./components/RetairPop09 copy.vue')['default']
    EmptyComponents: typeof import('./components/empty-components.vue')['default']
    EmptyWithdrawPop: typeof import('./components/EmptyWithdrawPop.vue')['default']
    FirstLogin: typeof import('./components/FirstLogin.vue')['default']
    Foo: typeof import('./components/Foo.tsx')['default']
    HeaderBack: typeof import('./components/HeaderBack.vue')['default']
    HeaderInfo: typeof import('./components/HeaderInfo.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    LoginStatus: typeof import('./components/LoginStatus.vue')['default']
    MultilingualExample: typeof import('./components/MultilingualExample.vue')['default']
    OderDetail: typeof import('./components/OderDetail.vue')['default']
    OderDetailRecharge: typeof import('./components/OderDetailRecharge.vue')['default']
    QRCodePopup: typeof import('./components/QRCodePopup.vue')['default']
    RechargPop: typeof import('./components/RechargPop.vue')['default']
    RecordDetailPop: typeof import('./components/RecordDetailPop.vue')['default']
    RetairPop01: typeof import('./components/RetairPop01.vue')['default']
    RetairPop02: typeof import('./components/RetairPop02.vue')['default']
    RetairPop03: typeof import('./components/RetairPop03.vue')['default']
    RetairPop04: typeof import('./components/RetairPop04.vue')['default']
    RetairPop05: typeof import('./components/RetairPop05.vue')['default']
    RetairPop06: typeof import('./components/RetairPop06.vue')['default']
    RetairPop07: typeof import('./components/RetairPop07.vue')['default']
    RetairPop08: typeof import('./components/RetairPop08.vue')['default']
    RetairPop09: typeof import('./components/RetairPop09.vue')['default']
    RetairPop10: typeof import('./components/RetairPop10.vue')['default']
    'RetairPop10 copy': typeof import('./components/RetairPop10_bak.vue')['default']
    RetarirStep2: typeof import('./components/RetarirStep2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserInfo: typeof import('./components/UserInfo.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
