/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./components/Bar.tsx')['default']
    copy: typeof import('./components/RecordDetailPop.vueult']
    EmptyComponents: typeof import('./components/empty-components.vue')['default']
    Foo: typeof import('./components/Foo.tsx')['default']
    HeaderBack: typeof import('./components/HeaderBack.vue')['default']
    HeaderInfo: typeof import('./components/HeaderInfo.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    LoginStatus: typeof import('./components/LoginStatus.vue')['default']
    MultilingualExample: typeof import('./components/MultilingualExample.vue')['default']
    OderDetail: typeof import('./components/OderDetail.vue')['default']
    'OderDetail copy': typeof import('./components/retair01.vue')['default']
    OderDetailRechare: typeof import('./components/OderDetailRechare.vue')['default']
    OderDetailRecharge: typeof import('./components/OderDetailRecharge.vue')['default']
    RechargPop: typeof import./components/retairPop01.vue.vue')['default']
    RetarirStep2: typeof import(./components/RetairPop01.vueue')['default']
    RouterLink: typeof import('vue-rout./components/RetairPop02.vue
    RouterView: typeof import('vue-rout./components/RetairPop03.vue
    TheFooter: typeof import('./compone./components/RetairPop04.vue
    UserInfo: typeof import('./componen./components/RetairPop05.vue
    VanButton: typeof import('vant/es')./components/RecordDetailPop.vue
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanImage: typeof import('vant/es')['Image']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
