/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./components/Bar.tsx')['default']
    EmptyComponents: typeof import('./components/empty-components.vue')['default']
    Foo: typeof import('./components/Foo.tsx')['default']
    HeaderBack: typeof import('./components/HeaderBack.vue')['default']
    HeaderInfo: typeof import('./components/HeaderInfo.vue')['default']
    LoginStatus: typeof import('./components/LoginStatus.vue')['default']
    OderDetail: typeof import('./components/OderDetail.vue')['default']
    RechargPop: typeof import('./components/RechargPop.vue')['default']
    Record: typeof import('./components/Record.vue')['default']
    RetarirStep2: typeof import('./components/RetarirStep2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    UserInfo: typeof import('./components/UserInfo.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanImage: typeof import('vant/es')['Image']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
